spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/items_database?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: validate