spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart_database?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8071/eureka/
    instance:
      prefer-ip-address: true	

management:
  endpoint:
    shutdown:
      enabled: true